import hashlib

inventoryD_id = 129
randomD = 921
tD = ''
node_name = 'D'

#searches the database (txt file) for the given input 
def inventory_D_search(record_id):
     with open('D_inventory_db.txt') as f:
        lines = f.readlines()
        item_qty = ''
        for row in lines:
            id = record_id
            #checking if the id is in the line
            if row.find(id) != -1:
                #break the line up so we can get the qty
                print(row.split(','))
                split_row = row.split(',')
                #get the qty (2nd value)
                qty = split_row[1]
                return qty
            
#Calculate tD for aggregated t 
def calc_tD():
    from pkg_server import get_pkg_e
    from pkg_server import get_pkg_n
    #Get the pkg e (part of public key)
    pkg_e = get_pkg_e()
    pkg_n = get_pkg_n()
    tD = pow(randomD, pkg_e, pkg_n)
    return tD 

#calculates aggregated t using the others inventorys' ts
def d_calc_aggregated_t(tA, tB, tC, tD):
    from pkg_server import get_pkg_n
    pkg_n = get_pkg_n()
    t = (tA * tB * tC * tD) % pkg_n
    return t

#sends the public key (inventory id) 
def inv_D_key_req():
    return inventoryD_id  

#sends the private key (generated by the PKG)
def get_privkey_D():
    from pkg_server import get_priv_key
    gD = get_priv_key('D')
    return gD

#calculates partial signature
def d_calc_partial_sig(m, t, gJ):
    #get random number 
    randomJ = randomD
    #get pkg n
    from pkg_server import get_pkg_n
    pkg_n = get_pkg_n()
    #append message to t
    m = str(t) + m
    #hash message
    hash_m = hashlib.md5(m.encode()).hexdigest()
    #convert message to int 
    decimal_m = int(hash_m, 16)
    #Each signer also computes sj = gj*rj^H(t,m) mod n , this is then shared with eachother
    rJ_exp = pow(randomJ, decimal_m, pkg_n)
    sJ = (gJ * rJ_exp) % pkg_n
    return sJ

#Calculates the multi signature using the other inventorys' partial signatures
def d_calc_multisig(sA, sB, sC, sD):
    #get pkg n
    from pkg_server import get_pkg_n
    pkg_n = get_pkg_n()
    #calc
    s = (sA * sB * sC * sD) % pkg_n
    return s 






# Consensus
def pbft_vote_on_primary(data):
    # from pkg_server import get_privkey_D  # change per node
    from pkg_server import get_pkg_n
    import hashlib

    # Recompute validation
    s = data['s']
    qty = data['qty']
    t = data['agg_t']
    m = str(t) + str(qty)

    hash_m = hashlib.md5(m.encode()).hexdigest()
    decimal_m = int(hash_m, 16)

    # Recalculate the validation value
    new_t = pow(int(t), decimal_m, get_pkg_n())
    # Simulated verification return
    return new_t  # or any value representing "valid"
